// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: movie_purchase.proto

package tariff_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMoviePurchaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId         string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	MovieSlug      string   `protobuf:"bytes,2,opt,name=movie_slug,json=movieSlug,proto3" json:"movie_slug"`
	Price          int32    `protobuf:"varint,3,opt,name=price,proto3" json:"price"`
	ActiveHours    int32    `protobuf:"varint,4,opt,name=active_hours,json=activeHours,proto3" json:"active_hours"`
	MovieResources []string `protobuf:"bytes,5,rep,name=movie_resources,json=movieResources,proto3" json:"movie_resources"`
	Movie          string   `protobuf:"bytes,6,opt,name=movie,proto3" json:"movie"`
}

func (x *CreateMoviePurchaseRequest) Reset() {
	*x = CreateMoviePurchaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movie_purchase_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMoviePurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMoviePurchaseRequest) ProtoMessage() {}

func (x *CreateMoviePurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_purchase_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMoviePurchaseRequest.ProtoReflect.Descriptor instead.
func (*CreateMoviePurchaseRequest) Descriptor() ([]byte, []int) {
	return file_movie_purchase_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMoviePurchaseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateMoviePurchaseRequest) GetMovieSlug() string {
	if x != nil {
		return x.MovieSlug
	}
	return ""
}

func (x *CreateMoviePurchaseRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateMoviePurchaseRequest) GetActiveHours() int32 {
	if x != nil {
		return x.ActiveHours
	}
	return 0
}

func (x *CreateMoviePurchaseRequest) GetMovieResources() []string {
	if x != nil {
		return x.MovieResources
	}
	return nil
}

func (x *CreateMoviePurchaseRequest) GetMovie() string {
	if x != nil {
		return x.Movie
	}
	return ""
}

type CreateMoviePurchaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	MovieSlug   string `protobuf:"bytes,4,opt,name=movie_slug,json=movieSlug,proto3" json:"movie_slug"`
	Price       int32  `protobuf:"varint,2,opt,name=price,proto3" json:"price"`
	ActiveHours int32  `protobuf:"varint,3,opt,name=active_hours,json=activeHours,proto3" json:"active_hours"`
	Name        string `protobuf:"bytes,5,opt,name=name,proto3" json:"name"`
}

func (x *CreateMoviePurchaseResponse) Reset() {
	*x = CreateMoviePurchaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movie_purchase_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMoviePurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMoviePurchaseResponse) ProtoMessage() {}

func (x *CreateMoviePurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_purchase_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMoviePurchaseResponse.ProtoReflect.Descriptor instead.
func (*CreateMoviePurchaseResponse) Descriptor() ([]byte, []int) {
	return file_movie_purchase_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMoviePurchaseResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateMoviePurchaseResponse) GetMovieSlug() string {
	if x != nil {
		return x.MovieSlug
	}
	return ""
}

func (x *CreateMoviePurchaseResponse) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateMoviePurchaseResponse) GetActiveHours() int32 {
	if x != nil {
		return x.ActiveHours
	}
	return 0
}

func (x *CreateMoviePurchaseResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateMoviePurchaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status"`
}

func (x *UpdateMoviePurchaseRequest) Reset() {
	*x = UpdateMoviePurchaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movie_purchase_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMoviePurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMoviePurchaseRequest) ProtoMessage() {}

func (x *UpdateMoviePurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_purchase_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMoviePurchaseRequest.ProtoReflect.Descriptor instead.
func (*UpdateMoviePurchaseRequest) Descriptor() ([]byte, []int) {
	return file_movie_purchase_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateMoviePurchaseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMoviePurchaseRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CategoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Slug string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug"`
}

func (x *CategoryResponse) Reset() {
	*x = CategoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movie_purchase_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryResponse) ProtoMessage() {}

func (x *CategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_purchase_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryResponse.ProtoReflect.Descriptor instead.
func (*CategoryResponse) Descriptor() ([]byte, []int) {
	return file_movie_purchase_proto_rawDescGZIP(), []int{3}
}

func (x *CategoryResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type CountryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slug string `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
}

func (x *CountryResponse) Reset() {
	*x = CountryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movie_purchase_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountryResponse) ProtoMessage() {}

func (x *CountryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_purchase_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountryResponse.ProtoReflect.Descriptor instead.
func (*CountryResponse) Descriptor() ([]byte, []int) {
	return file_movie_purchase_proto_rawDescGZIP(), []int{4}
}

func (x *CountryResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CountryResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MovieObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title            string             `protobuf:"bytes,9,opt,name=title,proto3" json:"title"`
	Poster           string             `protobuf:"bytes,10,opt,name=poster,proto3" json:"poster"`
	Rating           float32            `protobuf:"fixed32,12,opt,name=rating,proto3" json:"rating"`
	Category         *CategoryResponse  `protobuf:"bytes,14,opt,name=category,proto3" json:"category"`
	Country          []*CountryResponse `protobuf:"bytes,16,rep,name=country,proto3" json:"country"`
	Lang             string             `protobuf:"bytes,18,opt,name=lang,proto3" json:"lang"`
	Slug             string             `protobuf:"bytes,19,opt,name=slug,proto3" json:"slug"`
	IsSerial         bool               `protobuf:"varint,20,opt,name=is_serial,json=isSerial,proto3" json:"is_serial"`
	ReleaseYearStart int32              `protobuf:"varint,22,opt,name=release_year_start,json=releaseYearStart,proto3" json:"release_year_start"`
	ReleaseYearEnd   int32              `protobuf:"varint,23,opt,name=release_year_end,json=releaseYearEnd,proto3" json:"release_year_end"`
	Description      string             `protobuf:"bytes,25,opt,name=description,proto3" json:"description"`
}

func (x *MovieObject) Reset() {
	*x = MovieObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movie_purchase_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovieObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieObject) ProtoMessage() {}

func (x *MovieObject) ProtoReflect() protoreflect.Message {
	mi := &file_movie_purchase_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieObject.ProtoReflect.Descriptor instead.
func (*MovieObject) Descriptor() ([]byte, []int) {
	return file_movie_purchase_proto_rawDescGZIP(), []int{5}
}

func (x *MovieObject) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MovieObject) GetPoster() string {
	if x != nil {
		return x.Poster
	}
	return ""
}

func (x *MovieObject) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *MovieObject) GetCategory() *CategoryResponse {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *MovieObject) GetCountry() []*CountryResponse {
	if x != nil {
		return x.Country
	}
	return nil
}

func (x *MovieObject) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *MovieObject) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *MovieObject) GetIsSerial() bool {
	if x != nil {
		return x.IsSerial
	}
	return false
}

func (x *MovieObject) GetReleaseYearStart() int32 {
	if x != nil {
		return x.ReleaseYearStart
	}
	return 0
}

func (x *MovieObject) GetReleaseYearEnd() int32 {
	if x != nil {
		return x.ReleaseYearEnd
	}
	return 0
}

func (x *MovieObject) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetMoviePurchaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Price       int32        `protobuf:"varint,4,opt,name=price,proto3" json:"price"`
	ActiveHours int32        `protobuf:"varint,5,opt,name=active_hours,json=activeHours,proto3" json:"active_hours"`
	Status      string       `protobuf:"bytes,6,opt,name=status,proto3" json:"status"`
	CreatedAt   string       `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt   string       `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	Movie       *MovieObject `protobuf:"bytes,9,opt,name=movie,proto3" json:"movie"`
}

func (x *GetMoviePurchaseResponse) Reset() {
	*x = GetMoviePurchaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movie_purchase_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMoviePurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoviePurchaseResponse) ProtoMessage() {}

func (x *GetMoviePurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_purchase_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoviePurchaseResponse.ProtoReflect.Descriptor instead.
func (*GetMoviePurchaseResponse) Descriptor() ([]byte, []int) {
	return file_movie_purchase_proto_rawDescGZIP(), []int{6}
}

func (x *GetMoviePurchaseResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetMoviePurchaseResponse) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetMoviePurchaseResponse) GetActiveHours() int32 {
	if x != nil {
		return x.ActiveHours
	}
	return 0
}

func (x *GetMoviePurchaseResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetMoviePurchaseResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetMoviePurchaseResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GetMoviePurchaseResponse) GetMovie() *MovieObject {
	if x != nil {
		return x.Movie
	}
	return nil
}

type GetAllMoviePurchaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MoviePurchases []*GetMoviePurchaseResponse `protobuf:"bytes,1,rep,name=movie_purchases,json=moviePurchases,proto3" json:"movie_purchases"`
	Count          int32                       `protobuf:"varint,2,opt,name=count,proto3" json:"count"`
	Page           int32                       `protobuf:"varint,3,opt,name=page,proto3" json:"page"`
}

func (x *GetAllMoviePurchaseResponse) Reset() {
	*x = GetAllMoviePurchaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movie_purchase_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllMoviePurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMoviePurchaseResponse) ProtoMessage() {}

func (x *GetAllMoviePurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_purchase_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMoviePurchaseResponse.ProtoReflect.Descriptor instead.
func (*GetAllMoviePurchaseResponse) Descriptor() ([]byte, []int) {
	return file_movie_purchase_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllMoviePurchaseResponse) GetMoviePurchases() []*GetMoviePurchaseResponse {
	if x != nil {
		return x.MoviePurchases
	}
	return nil
}

func (x *GetAllMoviePurchaseResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetAllMoviePurchaseResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetUserMoviePurchasesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page"`
	Limit    int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit"`
	UserId   string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id"`
	Lang     string   `protobuf:"bytes,4,opt,name=lang,proto3" json:"lang"`
	Statuses []string `protobuf:"bytes,5,rep,name=statuses,proto3" json:"statuses"`
}

func (x *GetUserMoviePurchasesRequest) Reset() {
	*x = GetUserMoviePurchasesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movie_purchase_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserMoviePurchasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMoviePurchasesRequest) ProtoMessage() {}

func (x *GetUserMoviePurchasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_purchase_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMoviePurchasesRequest.ProtoReflect.Descriptor instead.
func (*GetUserMoviePurchasesRequest) Descriptor() ([]byte, []int) {
	return file_movie_purchase_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserMoviePurchasesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserMoviePurchasesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserMoviePurchasesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserMoviePurchasesRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *GetUserMoviePurchasesRequest) GetStatuses() []string {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type GetAllUserMoviePurchasesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MoviePurchases []*GetMoviePurchaseResponse `protobuf:"bytes,1,rep,name=movie_purchases,json=moviePurchases,proto3" json:"movie_purchases"`
	Count          int32                       `protobuf:"varint,2,opt,name=count,proto3" json:"count"`
	Page           int32                       `protobuf:"varint,3,opt,name=page,proto3" json:"page"`
}

func (x *GetAllUserMoviePurchasesResponse) Reset() {
	*x = GetAllUserMoviePurchasesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movie_purchase_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllUserMoviePurchasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUserMoviePurchasesResponse) ProtoMessage() {}

func (x *GetAllUserMoviePurchasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_purchase_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUserMoviePurchasesResponse.ProtoReflect.Descriptor instead.
func (*GetAllUserMoviePurchasesResponse) Descriptor() ([]byte, []int) {
	return file_movie_purchase_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllUserMoviePurchasesResponse) GetMoviePurchases() []*GetMoviePurchaseResponse {
	if x != nil {
		return x.MoviePurchases
	}
	return nil
}

func (x *GetAllUserMoviePurchasesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetAllUserMoviePurchasesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

var File_movie_purchase_proto protoreflect.FileDescriptor

var file_movie_purchase_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x22, 0xcc,
	0x01, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x50, 0x75,
	0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f,
	0x73, 0x6c, 0x75, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x76, 0x69,
	0x65, 0x53, 0x6c, 0x75, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x68, 0x6f, 0x75, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x12, 0x27,
	0x0a, 0x0f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x76, 0x69, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x22, 0x99, 0x01,
	0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x50, 0x75, 0x72,
	0x63, 0x68, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x53, 0x6c, 0x75, 0x67, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x68, 0x6f, 0x75,
	0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x48, 0x6f, 0x75, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x44, 0x0a, 0x1a, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x3a, 0x0a, 0x10, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x22, 0x39, 0x0a, 0x0f, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c,
	0x75, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xfb, 0x02, 0x0a, 0x0b, 0x4d, 0x6f, 0x76, 0x69, 0x65,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x70, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f,
	0x73, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x34, 0x0a, 0x08,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x12, 0x31, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x10, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x2e, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x07, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x12, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75,
	0x67, 0x18, 0x13, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x12, 0x1b, 0x0a,
	0x09, 0x69, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x14, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x69, 0x73, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x2c, 0x0a, 0x12, 0x72, 0x65,
	0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x79, 0x65, 0x61, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x18, 0x16, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x59,
	0x65, 0x61, 0x72, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x72, 0x65, 0x6c, 0x65,
	0x61, 0x73, 0x65, 0x5f, 0x79, 0x65, 0x61, 0x72, 0x5f, 0x65, 0x6e, 0x64, 0x18, 0x17, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0e, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x59, 0x65, 0x61, 0x72, 0x45,
	0x6e, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x19, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0xe4, 0x01, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69,
	0x65, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x5f, 0x68, 0x6f, 0x75, 0x72, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x29, 0x0a, 0x05, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x22, 0x92, 0x01, 0x0a, 0x1b,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x50, 0x75, 0x72, 0x63, 0x68,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0f, 0x6d,
	0x6f, 0x76, 0x69, 0x65, 0x5f, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x2e, 0x47, 0x65,
	0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x50, 0x75, 0x72,
	0x63, 0x68, 0x61, 0x73, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x22, 0x91, 0x01, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x6f, 0x76, 0x69,
	0x65, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x65, 0x73, 0x22, 0x97, 0x01, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x55,
	0x73, 0x65, 0x72, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0f, 0x6d, 0x6f, 0x76,
	0x69, 0x65, 0x5f, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x2e, 0x47, 0x65, 0x74, 0x4d,
	0x6f, 0x76, 0x69, 0x65, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x50, 0x75, 0x72, 0x63, 0x68,
	0x61, 0x73, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x42, 0x19,
	0x5a, 0x17, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x61, 0x72, 0x69, 0x66,
	0x66, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_movie_purchase_proto_rawDescOnce sync.Once
	file_movie_purchase_proto_rawDescData = file_movie_purchase_proto_rawDesc
)

func file_movie_purchase_proto_rawDescGZIP() []byte {
	file_movie_purchase_proto_rawDescOnce.Do(func() {
		file_movie_purchase_proto_rawDescData = protoimpl.X.CompressGZIP(file_movie_purchase_proto_rawDescData)
	})
	return file_movie_purchase_proto_rawDescData
}

var file_movie_purchase_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_movie_purchase_proto_goTypes = []interface{}{
	(*CreateMoviePurchaseRequest)(nil),       // 0: tariff.CreateMoviePurchaseRequest
	(*CreateMoviePurchaseResponse)(nil),      // 1: tariff.CreateMoviePurchaseResponse
	(*UpdateMoviePurchaseRequest)(nil),       // 2: tariff.UpdateMoviePurchaseRequest
	(*CategoryResponse)(nil),                 // 3: tariff.CategoryResponse
	(*CountryResponse)(nil),                  // 4: tariff.CountryResponse
	(*MovieObject)(nil),                      // 5: tariff.MovieObject
	(*GetMoviePurchaseResponse)(nil),         // 6: tariff.GetMoviePurchaseResponse
	(*GetAllMoviePurchaseResponse)(nil),      // 7: tariff.GetAllMoviePurchaseResponse
	(*GetUserMoviePurchasesRequest)(nil),     // 8: tariff.GetUserMoviePurchasesRequest
	(*GetAllUserMoviePurchasesResponse)(nil), // 9: tariff.GetAllUserMoviePurchasesResponse
}
var file_movie_purchase_proto_depIdxs = []int32{
	3, // 0: tariff.MovieObject.category:type_name -> tariff.CategoryResponse
	4, // 1: tariff.MovieObject.country:type_name -> tariff.CountryResponse
	5, // 2: tariff.GetMoviePurchaseResponse.movie:type_name -> tariff.MovieObject
	6, // 3: tariff.GetAllMoviePurchaseResponse.movie_purchases:type_name -> tariff.GetMoviePurchaseResponse
	6, // 4: tariff.GetAllUserMoviePurchasesResponse.movie_purchases:type_name -> tariff.GetMoviePurchaseResponse
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_movie_purchase_proto_init() }
func file_movie_purchase_proto_init() {
	if File_movie_purchase_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_movie_purchase_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMoviePurchaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_movie_purchase_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMoviePurchaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_movie_purchase_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMoviePurchaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_movie_purchase_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_movie_purchase_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_movie_purchase_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovieObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_movie_purchase_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMoviePurchaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_movie_purchase_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllMoviePurchaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_movie_purchase_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserMoviePurchasesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_movie_purchase_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllUserMoviePurchasesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_movie_purchase_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_movie_purchase_proto_goTypes,
		DependencyIndexes: file_movie_purchase_proto_depIdxs,
		MessageInfos:      file_movie_purchase_proto_msgTypes,
	}.Build()
	File_movie_purchase_proto = out.File
	file_movie_purchase_proto_rawDesc = nil
	file_movie_purchase_proto_goTypes = nil
	file_movie_purchase_proto_depIdxs = nil
}
