// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: uploaded_file.proto

package content_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUploadedFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resized   bool   `protobuf:"varint,1,opt,name=resized,proto3" json:"resized"`
	Slug      string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug"`
	Type      string `protobuf:"bytes,3,opt,name=type,proto3" json:"type"`
	Season    int32  `protobuf:"varint,4,opt,name=season,proto3" json:"season"`
	Episode   int32  `protobuf:"varint,5,opt,name=episode,proto3" json:"episode"`
	Extension string `protobuf:"bytes,6,opt,name=extension,proto3" json:"extension"`
}

func (x *CreateUploadedFileRequest) Reset() {
	*x = CreateUploadedFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uploaded_file_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUploadedFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadedFileRequest) ProtoMessage() {}

func (x *CreateUploadedFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_uploaded_file_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadedFileRequest.ProtoReflect.Descriptor instead.
func (*CreateUploadedFileRequest) Descriptor() ([]byte, []int) {
	return file_uploaded_file_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUploadedFileRequest) GetResized() bool {
	if x != nil {
		return x.Resized
	}
	return false
}

func (x *CreateUploadedFileRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateUploadedFileRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateUploadedFileRequest) GetSeason() int32 {
	if x != nil {
		return x.Season
	}
	return 0
}

func (x *CreateUploadedFileRequest) GetEpisode() int32 {
	if x != nil {
		return x.Episode
	}
	return 0
}

func (x *CreateUploadedFileRequest) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

type GetAllUploadedFileRequst struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resized bool   `protobuf:"varint,1,opt,name=resized,proto3" json:"resized"`
	Slug    string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug"`
	Type    string `protobuf:"bytes,3,opt,name=type,proto3" json:"type"`
}

func (x *GetAllUploadedFileRequst) Reset() {
	*x = GetAllUploadedFileRequst{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uploaded_file_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllUploadedFileRequst) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUploadedFileRequst) ProtoMessage() {}

func (x *GetAllUploadedFileRequst) ProtoReflect() protoreflect.Message {
	mi := &file_uploaded_file_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUploadedFileRequst.ProtoReflect.Descriptor instead.
func (*GetAllUploadedFileRequst) Descriptor() ([]byte, []int) {
	return file_uploaded_file_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllUploadedFileRequst) GetResized() bool {
	if x != nil {
		return x.Resized
	}
	return false
}

func (x *GetAllUploadedFileRequst) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *GetAllUploadedFileRequst) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type UploadedFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resized   bool   `protobuf:"varint,1,opt,name=resized,proto3" json:"resized"`
	Slug      string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug"`
	Type      string `protobuf:"bytes,3,opt,name=type,proto3" json:"type"`
	Season    int32  `protobuf:"varint,4,opt,name=season,proto3" json:"season"`
	Episode   int32  `protobuf:"varint,5,opt,name=episode,proto3" json:"episode"`
	Id        string `protobuf:"bytes,6,opt,name=id,proto3" json:"id"`
	CreatedAt string `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt string `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	Extension string `protobuf:"bytes,9,opt,name=extension,proto3" json:"extension"`
}

func (x *UploadedFile) Reset() {
	*x = UploadedFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uploaded_file_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadedFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadedFile) ProtoMessage() {}

func (x *UploadedFile) ProtoReflect() protoreflect.Message {
	mi := &file_uploaded_file_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadedFile.ProtoReflect.Descriptor instead.
func (*UploadedFile) Descriptor() ([]byte, []int) {
	return file_uploaded_file_proto_rawDescGZIP(), []int{2}
}

func (x *UploadedFile) GetResized() bool {
	if x != nil {
		return x.Resized
	}
	return false
}

func (x *UploadedFile) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *UploadedFile) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UploadedFile) GetSeason() int32 {
	if x != nil {
		return x.Season
	}
	return 0
}

func (x *UploadedFile) GetEpisode() int32 {
	if x != nil {
		return x.Episode
	}
	return 0
}

func (x *UploadedFile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadedFile) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UploadedFile) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *UploadedFile) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

type UpdateUploadedFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resized bool   `protobuf:"varint,1,opt,name=resized,proto3" json:"resized"`
	Id      string `protobuf:"bytes,2,opt,name=id,proto3" json:"id"`
}

func (x *UpdateUploadedFile) Reset() {
	*x = UpdateUploadedFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uploaded_file_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUploadedFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUploadedFile) ProtoMessage() {}

func (x *UpdateUploadedFile) ProtoReflect() protoreflect.Message {
	mi := &file_uploaded_file_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUploadedFile.ProtoReflect.Descriptor instead.
func (*UpdateUploadedFile) Descriptor() ([]byte, []int) {
	return file_uploaded_file_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUploadedFile) GetResized() bool {
	if x != nil {
		return x.Resized
	}
	return false
}

func (x *UpdateUploadedFile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAllUploadedFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Objects []*UploadedFile `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects"`
}

func (x *GetAllUploadedFileResponse) Reset() {
	*x = GetAllUploadedFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uploaded_file_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllUploadedFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUploadedFileResponse) ProtoMessage() {}

func (x *GetAllUploadedFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_uploaded_file_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUploadedFileResponse.ProtoReflect.Descriptor instead.
func (*GetAllUploadedFileResponse) Descriptor() ([]byte, []int) {
	return file_uploaded_file_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllUploadedFileResponse) GetObjects() []*UploadedFile {
	if x != nil {
		return x.Objects
	}
	return nil
}

var File_uploaded_file_proto protoreflect.FileDescriptor

var file_uploaded_file_proto_rawDesc = []byte{
	0x0a, 0x13, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0xad,
	0x01, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65,
	0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x72, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72,
	0x65, 0x73, 0x69, 0x7a, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x70, 0x69, 0x73, 0x6f, 0x64,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x70, 0x69, 0x73, 0x6f, 0x64, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x5c,
	0x0a, 0x18, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65,
	0x73, 0x69, 0x7a, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x65, 0x73,
	0x69, 0x7a, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xee, 0x01, 0x0a,
	0x0c, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x72, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x72, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x70, 0x69, 0x73, 0x6f,
	0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x70, 0x69, 0x73, 0x6f, 0x64,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x3e, 0x0a,
	0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x46,
	0x69, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4d, 0x0a,
	0x1a, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x07, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x42, 0x1a, 0x5a, 0x18,
	0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_uploaded_file_proto_rawDescOnce sync.Once
	file_uploaded_file_proto_rawDescData = file_uploaded_file_proto_rawDesc
)

func file_uploaded_file_proto_rawDescGZIP() []byte {
	file_uploaded_file_proto_rawDescOnce.Do(func() {
		file_uploaded_file_proto_rawDescData = protoimpl.X.CompressGZIP(file_uploaded_file_proto_rawDescData)
	})
	return file_uploaded_file_proto_rawDescData
}

var file_uploaded_file_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_uploaded_file_proto_goTypes = []interface{}{
	(*CreateUploadedFileRequest)(nil),  // 0: content.CreateUploadedFileRequest
	(*GetAllUploadedFileRequst)(nil),   // 1: content.GetAllUploadedFileRequst
	(*UploadedFile)(nil),               // 2: content.UploadedFile
	(*UpdateUploadedFile)(nil),         // 3: content.UpdateUploadedFile
	(*GetAllUploadedFileResponse)(nil), // 4: content.GetAllUploadedFileResponse
}
var file_uploaded_file_proto_depIdxs = []int32{
	2, // 0: content.GetAllUploadedFileResponse.objects:type_name -> content.UploadedFile
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_uploaded_file_proto_init() }
func file_uploaded_file_proto_init() {
	if File_uploaded_file_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_uploaded_file_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUploadedFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uploaded_file_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllUploadedFileRequst); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uploaded_file_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadedFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uploaded_file_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUploadedFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uploaded_file_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllUploadedFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_uploaded_file_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_uploaded_file_proto_goTypes,
		DependencyIndexes: file_uploaded_file_proto_depIdxs,
		MessageInfos:      file_uploaded_file_proto_msgTypes,
	}.Build()
	File_uploaded_file_proto = out.File
	file_uploaded_file_proto_rawDesc = nil
	file_uploaded_file_proto_goTypes = nil
	file_uploaded_file_proto_depIdxs = nil
}
